language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

env:
  global:
  - NODE_ENV=test

install:
  - npm install

services:
  - postgresql

script:
  - npm run test

after_success:
  - npm run coveralls
